title: "Albert Wiryawan"
description: "Professional portfolio showcasing development expertise and projects"
baseurl: "/avw-portfolio"
url: "https://albertwiryawan.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/

# Professional theme settings
theme: minima
minima:
  skin: classic

# Navigation
header_pages:
  - about.md
  - projects.md
  - experience.md
  - contact.md

# Social links (update with your actual usernames)
github_username: albertwir314
linkedin_username: albert-wiryawan

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:name/

# SEO settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - CLAUDE.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Professional settings
author: Albert Wiryawan
email: albertvw99@gmail.com
timezone: America/New_York